'use client'

import '@/app/globals.css'
import { Inter } from 'next/font/google'
import {Provider} from "react-redux";
const inter = Inter({ subsets: ['latin'] })

import {persistor, store} from "@/store";
import { PersistGate } from 'redux-persist/integration/react'

import Nav from "@/components/header/nav";

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
      <title>Tes</title>
    </head>
    <body className={inter.className}>
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <Nav/>
        <main className="container relative py-6 lg:py-8">
          {children}
        </main>
      </PersistGate>
    </Provider>
    </body>
    </html>
  )
}
